### Base
@host = http://localhost:8080
@form = application/x-www-form-urlencoded
@json = application/json

### GET /register (should be 200, body "register")
GET {{host}}/register

### POST /register (form-encoded)
POST {{host}}/register
Content-Type: {{json}}

{
  "username": "bob",
  "email": "bob@bob.bob",
  "password": "passabc"
}

### GET /login (should be 200, body "login")
GET {{host}}/login

### POST /login 
POST {{host}}/login
Content-Type: {{json}}

{
  "username": "bob",
  "email": "bob@bob.bob",
  "password": "passabc"
}

### Get /me (should show user bob)
GET  {{host}}/me

### POST /logout 
POST  {{host}}/logout

### Get /me (should now show anonymous user)
GET  {{host}}/me