### Base
@host = http://localhost:8080
@form = application/x-www-form-urlencoded
@json = application/json

### GET /register (should be 200, body "register")
GET {{host}}/register

### POST /register (form-encoded)
POST {{host}}/register
Content-Type: {{form}}

username=alice&password=pass123

### GET /login (should be 200, body "login")
GET {{host}}/login

### POST /login (form-encoded; your current handler just echoes "login")
POST {{host}}/login
Content-Type: {{form}}

username=alice&password=pass123


